#!/usr/bin/env python3
"""O ENDERECO CANONICO ESTA SERVINDO O QUE A ILHA ACABOU DE PUBLICAR?

    python3 ferramentas/conferir-cache-do-host.py .

O "PRONTO QUANDO" DO DESPACHO DE PRIORIDADE ALTA da Fundacao, aberto em
14/09/2026 em `dados/despachos.md`: "as tres ilhas tiverem, no conferir-no-ar.py
de cada uma, uma afirmacao que poe o endereco canonico contra o mesmo endereco
com quebra de cache, e ela passar". A robometria e a clubedomosaico ja tinham;
o despacho terminava com "Falta a aquametria". Este arquivo e essa afirmacao.

O QUE O DESPACHO SUPUNHA SOBRE ESTA ILHA, e a metade errada e a que interessa.
Ele registrou, medindo a home em 14/09, que a aquametria "nao traz a assinatura"
`<!--Generated by Endurance Page Cache-->` e que "nao foi medido pagina por
pagina". Medido aqui em 15/09/2026 as 11h18Z, nas 40 URLs do sitemap, com
cabecalho e corpo na MESMA requisicao (`curl -D - -o`, como a secao 4 do
contrato exige depois de uma conclusao errada ter custado quatro revisoes na
robometria): a assinatura realmente NAO aparece no corpo — e os CABECALHOS
nomeiam as duas camadas assim mesmo, `x-server-cache: true` nas 40 e
`x-proxy-cache` com HIT/MISS, sob `cache-control: max-age=7200`.

**A ausencia da assinatura nunca foi prova de ausencia do cache.** Era a regua
procurando um comentario no corpo quando a camada se anuncia no cabecalho —
a mesma familia do `conferir-no-ar.py` da robometria que aprovou a revisao 37
com 167 afirmacoes verdadeiras sobre uma pagina de horas antes. Por isso a
secao 1 desta ferramenta afirma sobre o CABECALHO: uma ilha que deixar de ter
cache no hospedeiro tem de fazer esta regua falar, nao emudecer.

COMO SE MEDE, e por que assim. O mesmo endereco e pedido DUAS vezes, uma limpa e
outra com uma chave de quebra de cache. A versao com chave nao pode ser cacheada,
entao ela e o que o WordPress produz AGORA; a limpa e o que o LEITOR recebe. As
duas tem de dizer a mesma coisa. Comparar bytes daria falso alarme — a chave
aparece no canonical e em todo link interno —, entao a comparacao e sobre o que
o leitor ve: marcacao fora, entidade desfeita, espaco juntado.

A PURGA NAO E INSTANTANEA, e isso e numero e nao desculpa. A unica medicao que o
arquipelago tem e da robometria: Sync da revisao 43 as 19h30:50Z, canonico
virado as 19h33:36Z — 166 segundos. `PURGA_ORCAMENTO_S` e o dobro arredondado:
largo o bastante para a janela conhecida nao virar alarme falso, estreito o
bastante para "o leitor ficou na pagina de antes" continuar reprovando. Quem
medir um atraso maior sobe ESTE numero e escreve a medicao ao lado — nunca apaga
a afirmacao. E o orcamento so e gasto quando ha desacordo: o caso comum nao paga
nada.

O QUE ESTA FERRAMENTA NAO PROVA, dito aqui porque a secao 4 do contrato cobra
exatamente isto de todo bloco publicavel. O bloco que a criou nao muda UMA
palavra de UMA pagina: ele instala a purga e o portao dela. Entao nao existe
texto novo no ar para afirmar sobre, e inventar um seria a "regua que certifica
a pagina de ontem" com o sinal trocado. O que ele mudou e a CONCORDANCIA entre o
canonico e o recem-gerado, e e sobre ela que a secao 2 afirma, nas 40 URLs.
"""

import html
import json
import os
import re
import subprocess
import sys
import time

RAIZ = os.path.abspath(sys.argv[1].rstrip("/") if len(sys.argv) > 1 else ".")
DOMINIO = "https://aquametria.com.br"
STATUS = DOMINIO + "/wp-json/aquametria/v1/status"
SITEMAP = DOMINIO + "/wp-sitemap.xml"

# `curl` sem Accept-Encoding pode receber uma variante de cache diferente da que
# o navegador e o Googlebot recebem — na robometria, uma copia de tres dias
# antes. Toda conferencia no ar desta fabrica manda `identity` (secao 4).
ACCEPT_ENCODING = "Accept-Encoding: identity"

# O ORCAMENTO DA PURGA, declarado e nao adivinhado — a medicao que o sustenta
# esta no cabecalho deste arquivo.
PURGA_ORCAMENTO_S = 360
PURGA_INTERVALO_S = 15

feitos = [0]
falhas = [0]


def ok(cond, rotulo, detalhe=""):
    feitos[0] += 1
    if not cond:
        falhas[0] += 1
        print("  FALHA  %s%s" % (rotulo, ("  (%s)" % detalhe) if detalhe else ""))
    return cond


def buscar(url, tentativas=3):
    """Cabecalho e corpo na MESMA requisicao, sempre.

    A LICAO DE METODO QUE CUSTOU QUATRO REVISOES NA ROBOMETRIA: um `curl -I`
    seguido de um `curl` mede dois instantes e conclui sobre um. Com o cache
    virando, as duas requisicoes pegam estados diferentes — foi assim que um
    `no-store` sem `last-modified`, que era o retrato de um arquivo de cache
    sendo apagado naquele segundo, virou prova de que a camada estava fora do
    alcance do PHP, e uma correcao que funcionava foi retirada por isso.

    Uma falha de rede so vira bloqueio depois de repetir (secao 20.2).
    """
    for _ in range(tentativas):
        r = subprocess.run(["curl", "-s", "-D", "-", "-H", ACCEPT_ENCODING,
                            "--max-time", "40", url],
                           capture_output=True, text=True)
        cab, corpo = separar(r.stdout)
        if corpo:
            return cab, corpo
        time.sleep(4)
    return "", ""


def separar(bruto):
    """Corta o que veio do `curl -D -` em cabecalho e corpo.

    NAO se procura `<!DOCTYPE` nem `<html`: o sitemap e XML e o `/status` e
    JSON, e uma regua que so sabe achar HTML devolveria corpo vazio para os dois
    — aprovando zero URL e chamando isso de verde. O corte e pela linha em
    branco que separa cabecalho de corpo em HTTP, repetida enquanto o que sobra
    ainda comecar por `HTTP/`, porque o proxy desta nuvem responde um
    `200 Connection Established` ANTES do cabecalho de verdade.
    """
    cabecalhos = []
    resto = bruto
    while resto.startswith("HTTP/"):
        for sep in ("\r\n\r\n", "\n\n"):
            i = resto.find(sep)
            if i >= 0:
                cabecalhos.append(resto[:i])
                resto = resto[i + len(sep):]
                break
        else:
            return "\n".join(cabecalhos) + resto, ""
    return "\n".join(cabecalhos), resto


def cabecalho(cab, nome):
    m = re.search(r"^%s:\s*(.+)$" % re.escape(nome), cab, re.I | re.M)
    return m.group(1).strip() if m else ""


def impressao_do_leitor(corpo, chave):
    """O QUE O LEITOR VE, reduzido a uma string comparavel.

    Tira marcacao, desfaz entidade e junta espaco: o que sobra e a palavra na
    tela. A CHAVE DE QUEBRA DE CACHE SAI ANTES, porque ela aparece dentro de
    link interno e do canonical da propria pagina — compara-la seria garantir
    desacordo e chamar isso de defeito.
    """
    corpo = corpo.replace("?" + chave, "").replace("&" + chave, "")
    texto = re.sub(r"(?is)<(script|style)[^>]*>.*?</\1>", " ", corpo)
    texto = re.sub(r"(?s)<[^>]+>", " ", texto)
    return re.sub(r"\s+", " ", html.unescape(texto)).strip()


def urls_do_sitemap():
    """A LISTA NASCE DO SITEMAP, NUNCA DIGITADA.

    Lista de URL escrita a mao e a mesma familia do numero de tela digitado da
    secao 8: nasce certa e envelhece calada na primeira leva. Se o sitemap
    responder vazio, a ferramenta REPROVA em vez de aprovar zero pagina — regua
    que aprova o vazio e a forma mais barata de ficar verde para sempre.
    """
    _cab, corpo = buscar(SITEMAP)
    indices = re.findall(r"<loc>([^<]+)</loc>", corpo)
    urls = []
    for i in indices:
        _c, xml = buscar(i)
        urls.extend(re.findall(r"<loc>([^<]+)</loc>", xml))
    return urls


def main():
    print("=" * 74)
    print("CACHE DO HOSPEDEIRO — o canonico contra o recem-gerado")
    print("=" * 74)

    with open(os.path.join(RAIZ, "manifest.json"), encoding="utf-8") as f:
        revisao_esperada = json.load(f)["revisao"]

    print("\n0. A REVISAO APLICADA E A DO MANIFEST")
    _c, corpo = buscar(STATUS)
    try:
        estado = json.loads(corpo)
    except Exception:
        estado = {}
    ok(estado.get("revisao") == revisao_esperada,
       "a revisao aplicada e a do manifest",
       "ar %s / manifest %s" % (estado.get("revisao"), revisao_esperada))

    urls = urls_do_sitemap()
    print("\nURLs no sitemap: %d" % len(urls))
    ok(len(urls) > 0, "o sitemap devolveu pelo menos uma URL", "%d" % len(urls))
    if not urls:
        print("\nREPROVADO NO AR: sem URL para medir.")
        return 1

    print("\n1. A CAMADA DE CACHE SE ANUNCIA NO CABECALHO")
    print("   (o corpo nao traz a assinatura do Endurance; o cabecalho traz —")
    print("    e foi procurar no corpo que fez o despacho de 14/09 supor que")
    print("    esta ilha talvez nao tivesse cache nenhum)")
    cab, _corpo = buscar(urls[0])
    servidor = cabecalho(cab, "x-server-cache")
    proxy = cabecalho(cab, "x-proxy-cache")
    controle = cabecalho(cab, "cache-control")
    ok(bool(servidor) or bool(proxy),
       "o hospedeiro nomeia a camada de cache que a purga existe para esvaziar",
       "x-server-cache=%r x-proxy-cache=%r" % (servidor, proxy))
    print("       cache-control: %s" % (controle or "(ausente)"))

    print("\n2. O CANONICO ESTA SERVINDO O QUE FOI PUBLICADO?")
    chave = "aqm_quebra_de_cache=%d" % int(time.time())
    atraso_maior = 0
    quentes = 0
    for url in urls:
        caminho = url[len(DOMINIO):] or "/"
        sep = "&" if "?" in url else "?"
        cab_limpa, limpa = buscar(url)
        _c, agora = buscar(url + sep + chave)

        if cabecalho(cab_limpa, "x-proxy-cache").upper() == "HIT":
            quentes += 1

        alvo = impressao_do_leitor(agora, chave)
        atraso = 0
        if impressao_do_leitor(limpa, chave) != alvo:
            # A JANELA DA PURGA, gasta so quando ha desacordo — o caso comum
            # nao paga nada. O orcamento e DECLARADO: janela que cresce sozinha
            # vira "espera ate passar", que e o contrario de medir.
            inicio = time.time()
            while time.time() - inicio < PURGA_ORCAMENTO_S:
                time.sleep(PURGA_INTERVALO_S)
                _cl, limpa = buscar(url)
                atraso = int(time.time() - inicio)
                if impressao_do_leitor(limpa, chave) == alvo:
                    break
        atraso_maior = max(atraso_maior, atraso)
        ok(impressao_do_leitor(limpa, chave) == alvo,
           "%s: o TEXTO do canonico e o do recem-gerado" % caminho,
           "igual na hora" if not atraso else "igual depois de %d s" % atraso)

    print("\n   entradas de cache QUENTES no momento da medicao: %d de %d" % (quentes, len(urls)))
    print("   maior atraso medido ate o canonico concordar: %d s (orcamento %d s)"
          % (atraso_maior, PURGA_ORCAMENTO_S))

    print("\n" + "=" * 74)
    if falhas[0]:
        print("REPROVADO NO AR: %d afirmacoes, %d falha(s)." % (feitos[0], falhas[0]))
        return 1
    print("APROVADO NO AR: %d afirmacoes, 0 falha(s)." % feitos[0])
    return 0


if __name__ == "__main__":
    sys.exit(main())
